name: mol_upload_draw_cloud.py
channels:
  - conda-forge
dependencies:
  - python=3.7
  - rdkit=2022.03.2
  - numpy=1.21.*
  - pandas = 1.3.*
  - pillow
  - pip=22.1
  - pip:
    -streamlit-aggrid==0.2.*
